// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtqOuEhBNRaY9SqCIZQSd5baa_7zWOZTY',
    appId: '1:125143856037:web:596d278cabe5a4164fee4c',
    messagingSenderId: '125143856037',
    projectId: 'conpany-description',
    authDomain: 'conpany-description.firebaseapp.com',
    storageBucket: 'conpany-description.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOqyo55XwvbVzgDN8dEmKOCCGabnMKIPg',
    appId: '1:125143856037:android:e1ff560f6df53a864fee4c',
    messagingSenderId: '125143856037',
    projectId: 'conpany-description',
    storageBucket: 'conpany-description.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQiTNM75oEG_y1zBaivQhbcZ1fFhn9Y5M',
    appId: '1:125143856037:ios:d52e09853a4afcb54fee4c',
    messagingSenderId: '125143856037',
    projectId: 'conpany-description',
    storageBucket: 'conpany-description.appspot.com',
    iosClientId: '125143856037-39igs5ebssikq8t49d1qm51onnuo9o00.apps.googleusercontent.com',
    iosBundleId: 'com.example.companyDescription',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQiTNM75oEG_y1zBaivQhbcZ1fFhn9Y5M',
    appId: '1:125143856037:ios:11eafd54808318fd4fee4c',
    messagingSenderId: '125143856037',
    projectId: 'conpany-description',
    storageBucket: 'conpany-description.appspot.com',
    iosClientId: '125143856037-1lo83mk973fvfm85fr4qbok707gqcbv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.companyDescription.RunnerTests',
  );
}
